### ISSUE TITLE
Templates link 404s on the Interactive OBJKTs page

### ISSUE THREAD

**Issue by SableRaf** [teia-community/teia-docs#2]
Go to this page and click the templates link: 
https://github.com/teia-community/teia-docs/wiki/Interactive-OBJKTs

The link should either link to the templates on the hicetnunc repo, or the Teia repo should have a copy of the templates. 

The templates can be found here:
https://github.com/hicetnunc2000/hicetnunc/tree/develop/templates

**Comment by NoRulesJustFeels** [comment]
Fixed link

**Comment by melMass** [comment]
fixed in [wiki/fabdc7c519a96e9481666adb32ddda5ff483887e](https://github.com/teia-community/teia-docs/wiki/Interactive-OBJKTs/fabdc7c519a96e9481666adb32ddda5ff483887e)
