### ISSUE TITLE
Mint on teia

### ISSUE THREAD

**Issue by ffotila** [teia-community/teia-docs#3]
Hell,
I have an issue with my last mint
Showing me this about 1 our

I add image to attachent
Thanks

![2022-07-21 13 56 51](https://user-images.githubusercontent.com/109734496/180197965-24d76dad-a591-4535-b668-e2282ba37d06.jpg)

**Comment by merchantcoppola** [comment]
sorry for the late answer, these are common issues

in general, first try swapping, often swapping fixes the issue
if that fails you can always come to the #help channel on our discord and the indexer dev can fix the issue
